version: '3'

tasks:
  build:gql:
    cmds:
      - go run github.com/Yamashou/gqlgenc generate

  run:
    cmds:
      - go run main.go {{.CLI_ARGS}}
    env:
      GO_ENV: development

  tidy:
    cmds:
      - go mod tidy